# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlertWindow(object):
    def setupUi(self, AlertWindow):
        AlertWindow.setObjectName("AlertWindow")
        AlertWindow.resize(350, 220)
        AlertWindow.setMinimumSize(QtCore.QSize(350, 200))
        AlertWindow.setMaximumSize(QtCore.QSize(350, 300))
        self.centralwidget = QtWidgets.QWidget(AlertWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setMouseTracking(False)
        self.textBrowser.setAcceptDrops(False)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.setOpenLinks(False)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.browse_apk = QtWidgets.QPushButton(self.centralwidget)
        self.browse_apk.setStyleSheet("")
        self.browse_apk.setObjectName("browse_apk")
        self.gridLayout_2.addWidget(self.browse_apk, 1, 0, 1, 1)
        AlertWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AlertWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        AlertWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AlertWindow)
        self.statusbar.setObjectName("statusbar")
        AlertWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AlertWindow)
        QtCore.QMetaObject.connectSlotsByName(AlertWindow)

    def retranslateUi(self, AlertWindow):
        _translate = QtCore.QCoreApplication.translate
        AlertWindow.setWindowTitle(_translate("AlertWindow", "ALERT!"))
        self.textBrowser.setHtml(_translate("AlertWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#c50000;\">ALERT: The current APK in use is the DEMO APK. Please replace it with the correct APK to make sure revenue is generated</span></p></body></html>"))
        self.browse_apk.setText(_translate("AlertWindow", "SELECT APK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlertWindow = QtWidgets.QMainWindow()
    ui = Ui_AlertWindow()
    ui.setupUi(AlertWindow)
    AlertWindow.show()
    sys.exit(app.exec_())
