# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetAssist(object):
    def setupUi(self, WidgetAssist):
        WidgetAssist.setObjectName("WidgetAssist")
        WidgetAssist.resize(450, 450)
        WidgetAssist.setMinimumSize(QtCore.QSize(450, 450))
        WidgetAssist.setStyleSheet("background-color: rgb(197, 197, 197);")
        self.centralwidget = QtWidgets.QWidget(WidgetAssist)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.TEXT_WIN = QtWidgets.QTextBrowser(self.centralwidget)
        self.TEXT_WIN.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"font: 14pt \"Times New Roman\";\n"
"")
        self.TEXT_WIN.setObjectName("TEXT_WIN")
        self.gridLayout.addWidget(self.TEXT_WIN, 1, 0, 1, 1)
        self.PORT_WIN = QtWidgets.QLabel(self.centralwidget)
        self.PORT_WIN.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 16pt \"Times New Roman\";\n"
"border-radius: 5px;\n"
"text-align: center;")
        self.PORT_WIN.setText("")
        self.PORT_WIN.setObjectName("PORT_WIN")
        self.gridLayout.addWidget(self.PORT_WIN, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        WidgetAssist.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WidgetAssist)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuRetry = QtWidgets.QMenu(self.menubar)
        self.menuRetry.setObjectName("menuRetry")
        WidgetAssist.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WidgetAssist)
        self.statusbar.setObjectName("statusbar")
        WidgetAssist.setStatusBar(self.statusbar)
        self.reboot = QtWidgets.QAction(WidgetAssist)
        self.reboot.setObjectName("reboot")
        self.help = QtWidgets.QAction(WidgetAssist)
        self.help.setObjectName("help")
        self.shutdown = QtWidgets.QAction(WidgetAssist)
        self.shutdown.setObjectName("shutdown")
        self.helpbox = QtWidgets.QAction(WidgetAssist)
        self.helpbox.setObjectName("helpbox")
        self.retry_proc = QtWidgets.QAction(WidgetAssist)
        self.retry_proc.setObjectName("retry_proc")
        self.searcherr = QtWidgets.QAction(WidgetAssist)
        self.searcherr.setObjectName("searcherr")
        self.gotosearch = QtWidgets.QAction(WidgetAssist)
        self.gotosearch.setObjectName("gotosearch")
        self.menuMenu.addAction(self.reboot)
        self.menuMenu.addAction(self.shutdown)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.helpbox)
        self.menuRetry.addAction(self.retry_proc)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuRetry.menuAction())

        self.retranslateUi(WidgetAssist)
        QtCore.QMetaObject.connectSlotsByName(WidgetAssist)

    def retranslateUi(self, WidgetAssist):
        _translate = QtCore.QCoreApplication.translate
        WidgetAssist.setWindowTitle(_translate("WidgetAssist", "WidgetMain"))
        self.menuMenu.setTitle(_translate("WidgetAssist", "Menu"))
        self.menuRetry.setTitle(_translate("WidgetAssist", "Retry"))
        self.reboot.setText(_translate("WidgetAssist", "Reboot"))
        self.help.setText(_translate("WidgetAssist", "Help"))
        self.shutdown.setText(_translate("WidgetAssist", "Shutdown"))
        self.helpbox.setText(_translate("WidgetAssist", "Help"))
        self.retry_proc.setText(_translate("WidgetAssist", "Reset Device"))
        self.searcherr.setText(_translate("WidgetAssist", "Searcherr"))
        self.gotosearch.setText(_translate("WidgetAssist", "GoToSearch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetAssist = QtWidgets.QMainWindow()
    ui = Ui_WidgetAssist()
    ui.setupUi(WidgetAssist)
    WidgetAssist.show()
    sys.exit(app.exec_())
